variables:
  TAG: ${CI_COMMIT_REF_NAME}

build:
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${TAG} --no-cache .
    - docker push ${CI_REGISTRY_IMAGE}:${TAG}
  after_script:
    - docker logout registry.gitlab.com

deploy:
  stage: deploy
  image: alpine:latest
  variables:
    HOST: git.krig.cloud
    USER: dokku
    REPO: krig.io
    BRANCH: ${CI_COMMIT_REF_NAME}
  before_script:
    - apk add --no-cache openssh-client git
    - eval $(ssh-agent -s)
    - echo "${DEPLOY_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - echo "${DOKKU_IDENTITY}" > ~/.ssh/known_hosts
  script:
    - git remote set-url --add dokku ${USER}@${HOST}:${REPO}
    - git push dokku HEAD:${BRANCH} --force
  after_script:
    - ssh-add -D
  only:
    - master
    - knacka
